### ISSUE TITLE
请教大神，work机器占用的硬盘空间大吗，另外这玩意儿是不是单机器CPU核数跟主频越大，收益越高，还是说集群一堆小机器好点

### ISSUE THREAD

**Issue by lh232510** [suugee/phala-prb#1]

**Comment by suugee** [comment]
可以看下官方经济模型说明：https://wiki.phala.network/en-us/learn/tokenomics/tokenomics/

单机solo，至少需要2t nvme固态。集群去跑的话，集群节点机建议4T高速固态，worker则只需要64/128G系统盘即可。

worker机不跑node可以提升2个核心的计算性能，所以集群计算肯定是优于solo的。
